-- Migration: 20260928_contact_inquiries.sql
-- Description: Create contact_inquiries table for support triage, lead gen, and ticket management

CREATE TABLE IF NOT EXISTS contact_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    inquiry_type TEXT NOT NULL,
    order_number TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'spam')),
    user_id TEXT, -- Clerk user ID if logged in
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for admin lookups and customer status checks
CREATE INDEX IF NOT EXISTS idx_contact_inquiries_ticket ON contact_inquiries(ticket_id);
CREATE INDEX IF NOT EXISTS idx_contact_inquiries_email ON contact_inquiries(email);
CREATE INDEX IF NOT EXISTS idx_contact_inquiries_user_id ON contact_inquiries(user_id);

-- Enable Row Level Security (RLS)
ALTER TABLE contact_inquiries ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY "Service role full access on contact_inquiries" 
ON contact_inquiries FOR ALL 
USING (true) 
WITH CHECK (true);

-- Allow public insert access for incoming inquiries
CREATE POLICY "Public insert access on contact_inquiries" 
ON contact_inquiries FOR INSERT 
TO public 
WITH CHECK (true);
